#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

set -eux

MANIFEST_TOOL_VERSION=$(curl -s https://api.github.com/repos/estesp/manifest-tool/releases/latest | grep 'tag_name' | cut -d\" -f4)
curl -fsSL -o manifest-tool "https://github.com/estesp/manifest-tool/releases/download/${MANIFEST_TOOL_VERSION}/manifest-tool-linux-amd64"
chmod +x manifest-tool

# Push latest manifest
if [[ $DOCKER_TAG = "latest" ]]; then
    ./manifest-tool push from-spec multi-arch-manifest.latest.yml
fi

# Push tag manifest
TAG_REGEX="^[0-9.]+$"
if [[ $DOCKER_TAG =~ $TAG_REGEX ]]; then
    sed -i "s/DOCKER_TAG/$DOCKER_TAG/" multi-arch-manifest.tag.yml
    ./manifest-tool push from-spec multi-arch-manifest.tag.yml
fi
